# Generated by Django 4.2.9 on 2024-05-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('time', models.CharField(default='N/A', max_length=64)),
                ('capacityLeft', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('trip', models.ManyToManyField(blank=True, related_name='users', to='tripsystem.trip')),
            ],
        ),
    ]
